version: '3.7'

services:
  postgres:
    image: "postgres:12.2-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  broker_app:
    image: pactfoundation/pact-broker:2.52.2-1
    ports:
      - "9292:9292"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
