pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'mvn') {
                    sh '''
                        cd pact-consumer
                        mvn clean install -DskipTests
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                withMaven(maven: 'mvn') {
                    sh '''
                        cd pact-consumer
                        mvn test
                    '''
                }
            }
        }
        stage('Publish Pact') {
            steps {
                withMaven(maven: 'mvn') {
                    sh '''
                        cd pact-consumer
                        echo ${env.GIT_COMMIT}
                        echo ${env.GIT_BRANCH}
                        mvn pact:publish -Dconsumer-application.version=${env.GIT_COMMIT} -Dpact.tag=${env.GIT_BRANCH}
                    '''
                }
            }
        }
    }
}