pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'cd pact-consumer'
                maven('clean install -DskipTests')
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
    }
}