pipeline {
    agent any

    environment {
        RELEASE_VERSION = "${sh(returnStdout: true, script: "git rev-list HEAD --count").trim()}"
        PROVIDER_VERSION = "${RELEASE_VERSION}-${env.GIT_COMMIT.substring(0, 7)}"
    }

    stages {
        stage('Build') {
            steps {
                withMaven(maven: 'mvn') {
                    dir('pact-provider') {
                        sh 'mvn clean install -DskipTests'
                    }
                }
            }
        }
        stage('Test & Provider Test Publish Verification Report') {
            steps {
                withMaven(maven: 'mvn') {
                    dir('pact-provider') {
                        sh "mvn test -Dpact.provider.version=${PROVIDER_VERSION} -Dpactbroker.host=broker_app -Dpactbroker.port=9292"
                    }
                }
            }
        }
    }
}